<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lgvn14127" ignored="1" name="Test" tests="2" failures="1" timestamp="19 Mar 2018 06:31:46 GMT" time="13.857" errors="0">
  <testcase name="@BeforeMethod beforeMethod" time="0.0" classname="yahoo.testcases.TestBase">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.logigear.driver.DriverManager.createWebDriver(DriverManager.java:38)
	at yahoo.testcases.TestBase.beforeMethod(TestBase.java:38)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod beforeMethod -->
  <testcase name="loginSuccessfully" time="7.309" classname="yahoo.testcases.LoginSuccessfully2">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at yahoo.testcases.LoginSuccessfully2.loginSuccessfully(LoginSuccessfully2.java:23)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- loginSuccessfully -->
  <testcase name="loginSuccessfully" time="0.0" classname="yahoo.testcases.LoginSuccessfully3">
    <skipped/>
  </testcase> <!-- loginSuccessfully -->
  <testcase name="@BeforeSuite beforeSuite" time="0.0" classname="yahoo.testcases.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
</testsuite> <!-- Test -->
